-- ==============================================================================
-- SCHEMA SUPABASE : TOWER GARDEN / SHOWCASE IOT
-- Copiez-collez ce script dans l'éditeur SQL de votre dashboard Supabase.
-- ==============================================================================

-- 1. Table de télémétrie des capteurs (3x AHT20/BMP280 + 4x VEML7700)
CREATE TABLE IF NOT EXISTS public.sensor_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    device_id TEXT DEFAULT 'esp32-tower-1',
    
    -- Canal 0 : Zone Inférieure / Racinaire
    t0 NUMERIC(5,2),        -- Température AHT20 (°C)
    h0 NUMERIC(5,2),        -- Humidité relative AHT20 (%)
    p0 NUMERIC(6,2),        -- Pression BMP280 (hPa)
    vpd0 NUMERIC(4,2),      -- VPD calculé (kPa)
    
    -- Canal 1 : Zone Médiane
    t1 NUMERIC(5,2),
    h1 NUMERIC(5,2),
    p1 NUMERIC(6,2),
    vpd1 NUMERIC(4,2),
    
    -- Canal 2 : Zone Supérieure / Canopée
    t2 NUMERIC(5,2),
    h2 NUMERIC(5,2),
    p2 NUMERIC(6,2),
    vpd2 NUMERIC(4,2),
    
    -- Canaux 4 à 7 : Capteurs de lumière VEML7700
    lux4 NUMERIC(8,2),
    ppfd4 NUMERIC(6,2),     -- PAR (µmol/m²/s)
    lux5 NUMERIC(8,2),
    ppfd5 NUMERIC(6,2),
    lux6 NUMERIC(8,2),
    ppfd6 NUMERIC(6,2),
    lux7 NUMERIC(8,2),
    ppfd7 NUMERIC(6,2)
);

-- Index pour accélérer les requêtes d'historique
CREATE INDEX IF NOT EXISTS idx_telemetry_created_at ON public.sensor_telemetry (created_at DESC);

-- 2. Table des commandes matérielles sécurisées (Plein contrôle Admin)
CREATE TABLE IF NOT EXISTS public.device_commands (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    device_id TEXT DEFAULT 'esp32-tower-1',
    command TEXT NOT NULL,         -- 'PUMP_OVERRIDE', 'SET_LIGHT_DURATION', 'SET_LIGHT_PWM', 'REBOOT'
    payload JSONB DEFAULT '{}'::jsonb NOT NULL,
    status TEXT DEFAULT 'PENDING', -- 'PENDING', 'EXECUTED', 'FAILED', 'CANCELLED'
    executed_at TIMESTAMP WITH TIME ZONE,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_commands_status ON public.device_commands (status, created_at ASC);

-- 3. Sécurité RLS (Row Level Security)
ALTER TABLE public.sensor_telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_commands ENABLE ROW LEVEL SECURITY;

-- POLITIQUES SUR LA TÉLÉMÉTRIE :
-- Tout le monde (y compris les visiteurs anonymes) peut lire les données pour le showcase public
DROP POLICY IF EXISTS "Public read telemetry" ON public.sensor_telemetry;
CREATE POLICY "Public read telemetry" 
    ON public.sensor_telemetry FOR SELECT 
    USING (true);

-- Seul l'ESP32 (via clé secrète/service_role ou API Key dédiée) peut insérer des mesures
DROP POLICY IF EXISTS "Device insert telemetry" ON public.sensor_telemetry;
CREATE POLICY "Device insert telemetry" 
    ON public.sensor_telemetry FOR INSERT 
    WITH CHECK (true);

-- POLITIQUES SUR LES COMMANDES :
-- Tout le monde peut voir les commandes en cours (statut transparent)
DROP POLICY IF EXISTS "Public read commands" ON public.device_commands;
CREATE POLICY "Public read commands" 
    ON public.device_commands FOR SELECT 
    USING (true);

-- SEUL UN UTILISATEUR CONNECTÉ (ADMIN AUTHENTIFIÉ PAR JWT) PEUT ENVOYER DES ORDRES
DROP POLICY IF EXISTS "Admin only insert commands" ON public.device_commands;
CREATE POLICY "Admin only insert commands" 
    ON public.device_commands FOR INSERT 
    WITH CHECK (auth.role() = 'authenticated');

-- L'ESP32 peut marquer la commande comme EXECUTED
DROP POLICY IF EXISTS "Device update commands" ON public.device_commands;
CREATE POLICY "Device update commands" 
    ON public.device_commands FOR UPDATE 
    USING (true);

-- 4. Publication Realtime pour WebSockets (diffusion en direct vers le Frontend)
DO $$
BEGIN
  -- Ajout sécurisé des tables à la publication Realtime Supabase
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
  
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.sensor_telemetry;
  EXCEPTION WHEN duplicate_object THEN
    NULL;
  END;

  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.device_commands;
  EXCEPTION WHEN duplicate_object THEN
    NULL;
  END;
END $$;

-- 5. Données initiales (Seed avec votre trame matérielle réelle)
INSERT INTO public.sensor_telemetry (
    created_at, device_id,
    t0, h0, p0, vpd0,
    t1, h1, p1, vpd1,
    t2, h2, p2, vpd2,
    lux4, ppfd4,
    lux5, ppfd5,
    lux6, ppfd6,
    lux7, ppfd7
) VALUES (
    now(), 'esp32-tower-1',
    26.8, 60.7, 1003.5, 1.09,
    26.8, 63.1, 1004.7, 1.02,
    26.8, 62.6, 1002.8, 1.04,
    20.28, 0.30,
    7.83, 0.12,
    12.44, 0.19,
    4.61, 0.07
);
